### PR TITLE
grammar: teach atom about wake definitions

### PR DESCRIPTION
**Pull request by terpstra**
Code folding and better highlights

Not sure how to get atom to show syntax errors? tree-sitter knows.

### CODE REVIEW

**Comment by terpstra** [comment]
FYI, I had to fork as I can't commit here.

**Comment by terpstra** [comment]
Also, FYI, there is another repository called 'language-wake' we should either replace or retire.

**Comment by drom** [comment]
> Also, FYI, there is another repository called 'language-wake' we should either replace or retire.

deleted `language-wake`

**Comment by drom** [comment]
> FYI, I had to fork as I can't commit here.

I have added all `sifive/developers` you should have access now

**Pull request merged**
